### ISSUE TITLE
2018 Projects list not showing up

### ISSUE THREAD

**Issue by Rupal-IIITD** [rails-girls-summer-of-code/rgsoc-teams#1002] opened 2018-05-20 11:15 UTC
When you go to this page: https://teams.railsgirlssummerofcode.org/projects

It shows just blank and even if you click small "2018" tab, it still doesn't show anything.

Although it does show previous years' projects if you click on "2017" or "2016" tab.

2018 projects' list is inaccessible.

**Comment by ramonh** [comment] 2018-05-20 17:06
Hi @Rupal-IIITD, thanks very much for finding this issue!

I can confirm it. It appears that none of the projects are set to be selected. I'll look into this 🚀

**Comment by carpodaster** [comment] 2018-05-20 19:06
@ramonh This is probably a mix of teams not having been assigned to their projects, yet, the coding phase of the season not yet started, and the way we associate teams and projects (potentially related: #892)

**Comment by ramonh** [comment] 2018-05-20 19:32
Oh! Thanks @carpodaster I think you're right. Since the season started, looking at the [code](https://github.com/rails-girls-summer-of-code/rgsoc-teams/blob/master/app/controllers/projects_controller.rb#L29) and playing around in the console, the projects haven't been selected yet.

**Comment by ramonh** [comment] 2018-05-21 13:49
After a bit of research (and the help from @F3PiX!) I found the following:

We filter not only projects that have been accepted, [but also only ones from teams that have been accepted](https://github.com/rails-girls-summer-of-code/rgsoc-teams/blob/master/app/models/project.rb#L49). This is [specifically tested](https://github.com/rails-girls-summer-of-code/rgsoc-teams/blob/master/spec/controllers/projects_controller_spec.rb#L34) as such.

So @F3PiX, if you add a selected team to your test, it should pass.

The question is, do we want this behavior?

**Comment by F3PiX** [comment] 2018-05-21 16:57
@ramonh The team in the test is accepted.

**Comment by ramonh** [comment] 2018-05-21 17:00
My apologies @F3PiX I was testing it this morning and missed that!

**Comment by ramonh** [comment] 2018-05-21 17:06
This is stranger than I thought. I put a breakpoint into the index action during a test and found this:

```
[18] pry(#<ProjectsController>)> Project.all
=> [#<Project:0x00007fd89675d688
  id: 1,
  name: "Input Compressor",
  created_at: Mon, 21 May 2018 17:03:47 UTC +00:00,
  updated_at: Mon, 21 May 2018 17:03:47 UTC +00:00,
  submitter_id: 1,
  season_id: 1,
  mentor_name: "Video Viewer",
  mentor_github_handle: "suzi.monahan",
  mentor_email: "brittanie@dietrichherman.biz",
  url: "http://gutmann.us",
  description:
   "Whatever Pitchfork scenester mlkshk helvetica keytar. Fixie mixtape echo park stumptown blog. Pitchfork whatever chambray McSweeney's echo park artisan. Cliche high life lomo organic put a bird on it keytar Pitchfork retro.",
  issues_and_features: "valentine@rath.info",
  beginner_friendly: true,
  aasm_state: "accepted",
  tags: [],
  source_url: nil,
  comments_locked: false,
  code_of_conduct: nil,
  requirements: nil,
  license: nil>]
[19] pry(#<ProjectsController>)> Project.all.first
=> nil
[20] pry(#<ProjectsController>)> Project.first
=> nil
```

**Comment by ramonh** [comment] 2018-05-21 17:07
Aha! The project seems to be invalid, @F3PiX

**Comment by ramonh** [comment] 2018-06-12 14:45
This has been fixed by assigning the selected teams to their projects, as shown [here](https://teams.railsgirlssummerofcode.org/projects).

**Closed by ramonh** 2018-06-12 14:45 UTC
