### ISSUE TITLE
Bugs/Errors found during testing 

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#407] opened 2016-03-13 18:29 UTC
## MUST FIX 

+ [x] can't submit a completely filled out application, get an error that the team should have at least one mentor
+ [x] cost of living link-> faulty 
+ [X] ~~add buttons "next" and "back" to bottom of page, so indicate that you have to go through the next tabs in order to go through application~~ 
+ [x] check validity (assigned to @michaelem, improved in https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/409)
  + [x] should only be visible on last tab page
  + [x] should SAVE & check 

+ [x] doesn't save skill level (https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/192)
+ [x] doesn't give error message if not filled out:
  + [x] what do you want to achieve
  + [x] how did you get into programming
  + [x] how much money do you need (maybe just delete the "--" field)

+ [X] ~~can't change roles from e.g. student to coach: If I try to edit that team, changing anasofiapinho from student to coach or from coach to student, the mouse doesn't let me select.~~

+ [x] "Banking Information (1st student) can't be blank" -> field doesn't exist 

#### TEXT (assigned to maria)
  + [x] "Some of the guidelines are specific to ruby, but most are language-agnostic." - needs to be changed 
  + [x] "For how many months have you been learning the language of your chosen project?" - doesn't mention secondary project 
  + [ ] obligatory fields: state that all fields are obligatory
  + [x] "Tell us about your Rails Girls and community involvement."-> change to all initiatives 

+ [x] "minimum money" error message shows when you don't fill out the OPTIONAL text field underneath. 

#### UI: ERROR MESSAGE: (#408)

+ [x] "4 errors to go before you can apply:" <- this is invisible (red on red).
+ [x] error messages should tell you in which tab the info is missing 
+ [x] error messages not as a summary, but in selected fields (some error messages are shown directly in the field, some are not. this is confusing)
+ [x] some of error messages refer to ‘1st student’ and '2nd student’, and some - to ‘student0’ and ‘student1’. it would be nice if all messages looked the same (e.g. refer to ‘1st student’ and '2nd student’)

## ON THE FENCE

+ [ ] add pagination (e.g. 2/4) to bottom of page to show which tab you are on
+ [x] if i go to edit my team, i have random team members filled in but no roles selected 
+ [ ] 750-1000 words for essay: add word count to text field? 

#### TEXT
+ [x] "Since this is a self-guided program, how are you planning to work together?" -> this might need a bit more explanation. (in the works, see https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/410)
+ [ ] 1st student: not explained, who is 1st who second <- hard to fix

## NICE TO HAVE
+ [ ] "Please don't mention your name, age, or current location." -> should be bolder, on top of the text field
+ [ ] "my team" should be next to "my application" in menue 
+ [ ]  show progress (3/10) (make tabs green/ red for errors)
+ [x] It makes more sense to open links to Help and Guides in a new tab (e.g. Application guide on the Application form).

#### TEXT
+ [x] ERROR MESSAGES: red / black can't read -> should be black on white with a red border or sth. 
+ [ ] "For volunteer teams only" -> confusing. text needs to be changed
+ [ ] error message: should not be "please add another sutdent", but "please edit your team first"
+ [x] step by step process: 1. log in, then edit your team
+ [x] financial numbers: 1500+ is missing

**Comment by alicetragedy** [comment] 2016-03-13 18:33
cost of living fixed: https://github.com/rails-girls-summer-of-code/rgsoc-teams/commit/49da743b8968fa55db267b327e1c79b33d4ca0e0
error messages: removed banking info, added money, achieve, how did you get into programming https://github.com/rails-girls-summer-of-code/rgsoc-teams/commit/f2a2115d863aac0a49c28f63fd1eb9c9984a8f6c

**Comment by alicetragedy** [comment] 2016-03-13 20:13
@anikalindtner this -> https://github.com/rails-girls-summer-of-code/rgsoc-teams/commit/8ab7e5e4a4c8a7dd7fa9a8a15177ba27be449b9c should at least make the flash messages (the "pretty" error or info boxes) more bearable by adding a small button that can be used to dismiss the message.

**Comment by michaelem** [comment] 2016-03-13 20:41
is 'add buttons "next" and "back" to bottom of page, so indicate that you have to go through the next tabs in order to go through application' meant for the application draft form?

**Comment by anasofiapinho** [comment] 2016-03-13 21:36
Nice to have:
1. Can students edit other students information?
2. The order in which the errors are listed is not the same as the form and that causes a bit of confusion.

**Comment by carpodaster** [comment] 2016-03-14 08:14
> can't change roles from e.g. student to coach: If I try to edit that team, changing anasofiapinho from student to coach or from coach to student, the mouse doesn't let me select. 

That is WAI and is/was part of #205 + a85416d72d8c45a82f0111a8e15a11c123cd2940; the radio buttons are disabled.

**Comment by carpodaster** [comment] 2016-03-14 08:16
> doesn't save skill level (#192)

The skill level does get saved, it just doesn't pre-select the radio buttons. At least I can reproduce this problem locally now (which wasn't the case last year when we got all the bug reports). I'm still at a loss why that is so.

**Comment by carpodaster** [comment] 2016-03-14 12:57
> "my team" should be next to "my application" in menue

This, too, is subject to #380

**Comment by carpodaster** [comment] 2016-03-14 13:00
>  show progress (3/10) (make tabs green/ red for errors)

This is quite a task and also quite brittle in respect to future changes. I wouldn't want to assign resources to it right now.

**Comment by carpodaster** [comment] 2016-03-14 13:00
>  if i go to edit my team, i have random team members filled in but no roles selected 

I think I need a more concrete example for that

**Comment by carpodaster** [comment] 2016-03-14 14:20
> add buttons "next" and "back" to bottom of page, so indicate that you have to go through the next tabs in order to go through application

I don't think we can add this. For example the 2nd tab is not really a "next" tab since a student cannot edit the fields of their pair.

**Comment by anikalindtner** [comment] 2016-03-14 14:34
@carpodaster: if you click on "edit" you can see people added to your team that you didn't add. Like:

![screen shot 2016-03-14 at 15 30 03](https://cloud.githubusercontent.com/assets/1711357/13747697/ca8b88a6-e9f9-11e5-8a89-6037715b2a80.png)

I know that this looks a bit different for me, since I'm also an organizer, but my pair (who's a friend of mine and not an organizer) could also see this. 

+ as for the "doesn't save skill level": 
I'm not sure I understand your answer, but this happens: 
I select this:
![screen shot 2016-03-14 at 15 32 31](https://cloud.githubusercontent.com/assets/1711357/13747743/143a6526-e9fa-11e5-84d2-542627edef50.png)

After I click on "safe as draft", I get this:
![screen shot 2016-03-14 at 15 32 31](https://cloud.githubusercontent.com/assets/1711357/13747759/22418cee-e9fa-11e5-9756-ae86eae9ff02.png)

**Comment by carpodaster** [comment] 2016-03-14 15:13
@anikalindtner skill level issue: What I meant is that the underlying database record gets saved. The form just doesn't pre-select the value present in de DB

**Comment by carpodaster** [comment] 2016-03-14 15:14
@anikalindtner Can you give me the ID of the team in question please? Or its direct URL?

**Comment by alicetragedy** [comment] 2016-03-14 15:14
@carpodaster @anikalindtner it's weird, because for me, locally, it works.

**Comment by anikalindtner** [comment] 2016-03-14 16:08
@carpodaster https://rgsoc-teams-staging.herokuapp.com/teams/1/edit

**Comment by alicetragedy** [comment] 2016-03-14 21:08
@anikalindtner I just double-checked the info regarding your team in staging, and it seems like your team wasn't created yesterday, but it was created last year. So, I'm guessing that's why you have those roles in there — they were added last year to your team, and when you logged into the app you didn't create a new team but just added a student to your currently existing team. Could that be it?

**Comment by anikalindtner** [comment] 2016-03-14 23:01
@alicetragedy ah yes! exactly! Hat tip ms sherlock <3

**Comment by carpodaster** [comment] 2016-03-18 07:30
We are live!

**Comment by alicetragedy** [comment] 2016-03-18 08:15
so are the bugs! they've been released into the wild :trollface: :tada:

**Comment by anikalindtner** [comment] 2016-03-21 15:58
I'd love to keep track of this. and if someone has a minute they can fix some of the bugs listed here.

**Comment by carpodaster** [comment] 2016-03-21 16:08
@anikalindtner The must haves are fixed. I've commented on some of the others and among them are a few `wontfix`es (because they're not applicable). 

For text corrections: suggestions for better wording are most welcome.

If there are items left in this list, please add them as new issues. It's a lot easier to keep track of an atomic issue than aggregate ones like this.

This said: we are currently a bit swarmed with issues and I'd rather have issues closed that are of no immediate concern than having our issue / feature request list grow over 5+ pages.

**Closed by carpodaster** 2016-03-21 16:08 UTC

**Comment by alicetragedy** [comment] 2016-03-21 16:10
will take another look at the text-based fixes and adding the link to the team in the navigation, but I think that's all we will be able to deal with this year (ie. no progress bar, no pagination because it doesn't make sense from a UX point of view).
as @carpodaster said I think immediate items can be added as new issues. the text-based corrections will be fixed today still by me, so no need to add them separately!

**Comment by anikalindtner** [comment] 2016-03-21 16:12
awesome, laura thank you. feel free to close this then again after today.

**Comment by alicetragedy** [comment] 2016-03-21 16:27
Note: "state that all fields are obligatory" is not required anymore because a) not all fields are obligatory and b) we have finally fixed all of the error fields, so everything is showing properly now.
