### ISSUE TITLE
Radio Button Error

### ISSUE THREAD

**Issue by ShellyCoen** [rails-girls-summer-of-code/rgsoc-teams#194] opened 2015-04-13 16:34 UTC
I filled out my application and saved my skill level and how many months options. 
Up until a couple of days ago that kept the information but now after I save and exit the application, and then return to it, the radio buttons are no longer selected. 

To reproduce:
Select radio button and save application
Sign out and then back in

**Comment by carpodaster** [comment] 2015-04-13 16:35
hey @ShellyCoen – can you confirm that this is a duplicate of #192 ?

**Comment by ShellyCoen** [comment] 2015-04-13 16:38
My apologies, exact same problem! Should have read through the issues list

**Comment by carpodaster** [comment] 2015-04-13 16:39
No problem. We have a lot of open issues and no one is expected to read them all :smile: Allow me to close this. I can offer you this reply:

> To assure you: if the values are checked in your user profile, you're all good. It's weird that they don't show up in the application draft, and I have yet to get to the bottom of this, but the application data will be collected from your user profile once you hit 'Submit'.

Good luck with your application!

**Comment by ShellyCoen** [comment] 2015-04-13 16:40
Thank you! Keeping my fingers crossed!

**Closed by carpodaster** 2015-04-13 16:39 UTC
