### ISSUE TITLE
"Fork me on Github" badge overlaps with "Sign in"

### ISSUE THREAD

**Issue by daminisatya** [rails-girls-summer-of-code/rgsoc-teams#659] opened 2017-02-10 17:07 UTC
![image](https://cloud.githubusercontent.com/assets/6227784/22836214/791095fe-efe1-11e6-81ed-2358f5dbd79c.png)

**Comment by alicetragedy** [comment] 2017-02-11 16:31
could you give more details, e.g. which browser you're using, which device, your resolution, etc.. thanks!

**Comment by daminisatya** [comment] 2017-02-11 16:33
@alicetragedy Chrome browser, on HP laptop 13inch screen!

**Comment by alicetragedy** [comment] 2017-02-11 16:38
we will look into it! thanks for reporting this

**Comment by mweitzel** [comment] 2017-02-14 14:43
I have the same issue on an 11" Macbook Pro.

**Comment by carpodaster** [comment] 2017-03-09 21:10
I cannot reproduce this on a MBP 13". Has this secretly been fixed already?

**Comment by alicetragedy** [comment] 2017-03-09 21:23
@carpodaster no, it hasn't been secretly fixed 😭 I wanted to look into it because I saw it in a couple of other screenshots from applicants. Also not reproduceable on my MBP 13".

**Comment by juuh42dias** [comment] 2017-06-30 13:48
On my laptop Acer 15" has same problem. Reducing Width 70px from class Container would already solve the problem in my case.

![captura de tela de 2017-06-30 10-44-36](https://user-images.githubusercontent.com/1828204/27738233-28ad6cdc-5d81-11e7-84b2-2661b5a29a68.png)
![captura de tela de 2017-06-30 10-43-59](https://user-images.githubusercontent.com/1828204/27738232-28abfc12-5d81-11e7-85d7-a6ed0d77b5ef.png)

**Comment by juuh42dias** [comment] 2017-07-05 14:00
Hey @carpodaster , @alicetragedy , the problem persists :( i want sign that issue...

**Comment by carpodaster** [comment] 2017-07-05 20:25
@juuh42dias very cool, can you send a PR?

**Comment by carpodaster** [comment] 2017-09-05 17:53
@juuh42dias I've assigned you to this issue as you said you already have a working fix. Feel free to unassign yourself of course

**Comment by katiekeel** [comment] 2017-11-07 20:42
@carpodaster Hi there! I'm a first time contributor. I've written a solution based on @juuh42dias' screenshot and I'd be happy to submit it here.

**Comment by carpodaster** [comment] 2017-11-09 07:30
Hi @katiekeel – that's great! Could you do a pull request with your change?

Also: a very warm welcome 👋  😄

**Comment by katiekeel** [comment] 2017-12-08 17:25
@carpodaster Certainly! Sorry I forgot about this for a bit.

**Comment by inescoelho** [comment] 2017-12-16 14:50
Can I report here that, on my Ubuntu, I don't even see the ribbon?! 🙈🤣

![screenshot from 2017-12-16 14 43 08](https://user-images.githubusercontent.com/3616894/34071555-9e3f9196-e26f-11e7-9982-9b1b4e28d7ab.png)
![screenshot from 2017-12-16 14 46 55](https://user-images.githubusercontent.com/3616894/34071594-097b1cdc-e270-11e7-9515-b5af0a6608a5.png)

**Comment by klappradla** [comment] 2017-12-16 15:33
What's your screen resolution @inescoelho ? The badge is hidden for smaller widths than 1360px.

**Comment by inescoelho** [comment] 2017-12-16 17:20
You are right, @klappradla! My screen resolution is 1366 x 768, but since I have a lateral menu on ubuntu, the browser resolution is smaller and the badge is hidden. On my windows partition, the browser opens full length and I can see the badge! That's why I was confused and thought it was a ubuntu specific problem! :rofl:

**Comment by klappradla** [comment] 2018-04-29 10:16
Hey @daminisatya 👋 

This should be fixed via #986 (thanx to @katrin-k 🙏 ) - feel free to reopen the issue if the problem persists for you.

**Closed by klappradla** 2018-04-29 10:16 UTC
