### ISSUE TITLE
DB migration is failing on fresh database setup

### ISSUE THREAD

**Issue by Nattivolk** [rails-girls-summer-of-code/rgsoc-teams#387] opened 2016-03-06 19:34 UTC
bundle exec rake db:drop db:create db:migrate is not working on fresh database setup.

Reason is: 
- 20150625085615_add_seasons_to_mailings.rb is calling Mailing.update_all 
- which calls Season.current 
- which is depending on database column created in 20151205133354_add_project_proposal_dates_to_seasons.rb

This is not failing on travisCI, because we don't call db:drop here.

Workaround: Comment out line 4 in 20150625085615_add_seasons_to_mailings.rb -> Mailing.update_all(seasons: [Season.current.name])

**Comment by klappradla** [comment] 2016-03-06 19:39
Try to run `bundle exec rake db:drop db:setup` instead, this should work. I have a PR including this almost ready 😉

**Comment by Nattivolk** [comment] 2016-03-06 19:41
ok, that works as well :)
Are you updating the readme?

**Comment by klappradla** [comment] 2016-03-06 19:44
I can update it later, yes.
You may also want to change the activities from the seed data to have a `published_at` value if you want to look at the start page as far as I can recall.

**Comment by alicetragedy** [comment] 2016-03-06 21:48
I think this is a duplicate of https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/375 and it looks like there are some open PRs which are taking care of solving this problem already, which Carsten is in the process of reviewing. Sorry for the hassle :disappointed: 
@klappradla if you get a chance to update the readme, please feel free to do so. After the above mentioned PRs are merged we can remove your instructions again, but in the meanwhile it might help newcomers to get set up easily. Thanks!!! :sparkles:

**Comment by carpodaster** [comment] 2016-03-16 19:33
(I'm closing this as a duplicate in favor of the already existing #375)

**Closed by carpodaster** 2016-03-16 19:33 UTC
Labels: duplicate
