### ISSUE TITLE
create student dashboard

### ISSUE THREAD

**Issue by katrin-k** [rails-girls-summer-of-code/rgsoc-teams#60] opened 2014-02-22 11:31 UTC
Arne came up with the idea to have a dashboard providing a fast look at the latest acitvities in all coached/mentored/supervised teams to help realise when a team gets stuck. 

Below's a first sketch on how a dashboard could look like:

![draft rgsoc teams app dashboard](https://cloud.githubusercontent.com/assets/164400/16706834/af5f7362-45bb-11e6-839d-1fb073743e35.png)

**Comment by carpodaster** [comment] 2015-02-24 18:13
Possible duplicate of #109 ?

**Comment by carpodaster** [comment] 2016-07-09 08:22
Continued in #462

**Closed by carpodaster** 2016-07-09 08:22 UTC
Labels: rgsoc-2016, would be nice
