### ISSUE TITLE
Checked-up-on-them button (without comment) needs manual reload to show

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#285] opened 2015-07-20 19:34 UTC
While the Button with a comment works, clicking the button without a comment won't do anything. 

https://teams.railsgirlssummerofcode.org/teams/90

https://teams.railsgirlssummerofcode.org/teams/66

Might also have to do something with @alexwllms' profile? there seems to be a issue with his GH avatar not being shown. Maybe some weird underlying issue which prevents him from sending a "checked-up" without a comment.

**Comment by anikalindtner** [comment] 2015-07-20 19:55
any idea @carpodaster @alicetragedy ?

**Comment by alicetragedy** [comment] 2015-07-20 19:59
@anikalindtner the thing is that the blue button doesn't show its "result" right away, the page needs to be refreshed in order for one to see that "checked up on them" has been set. could it be that that's the problem? This is something that happens for all teams, and it was always like this – but probably needs fixing.

**Comment by anikalindtner** [comment] 2015-07-20 20:08
@alicetragedy huch! you are right! OMG! I tried it myself. (and I saw you did too) And yes, it probably should show up right away, because I also was really confused when nothing happened.

@alexwllms, ^ could you try that as well? Seems it worked for Laura and me. phewwww.. so we don't have a bug after all. wheee \o/ You just have to refresh the page to see the results of the blue button show up.

**Comment by alicetragedy** [comment] 2015-07-20 20:10
@anikalindtner well... not sure I would call that "not a bug" but at least we know where it comes from ;) 
#bugorfeature

**Comment by anikalindtner** [comment] 2015-07-20 21:26
@alicetragedy hehe very true indeed. at least it's not the bug i was expecting it to be, but seems to be one we already know about. 

i only now want to get a heads up from @alexwllms though that this indeed also works for him. (not trusting anything from the teams app anymore ;) )

**Comment by alexwllms** [comment] 2015-07-21 19:08
Works if the page is reloaded :)



—
Alex Williams
+44 (0) 7446 975976

**Comment by sareg0** [comment] 2015-07-21 19:09
does it have to be reloaded everytime?

**Comment by F3PiX** [comment] 2015-07-21 19:31
Can Ajax solve this? I would LOOOOVE to learn some Ajax....

**Comment by carpodaster** [comment] 2015-08-24 11:40
> Can Ajax solve this? I would LOOOOVE to learn some Ajax....

@F3PiX I haven't looked at the problem but it seems the form action already _is_ an Ajax one, only the corresponding div isn't updated. Maybe a DOM ID has been renamed?

**Comment by F3PiX** [comment] 2015-09-23 07:41
This one is solved by #311. Shall we close it?

**Comment by carpodaster** [comment] 2015-09-23 08:18
I think so :)

**Closed by carpodaster** 2015-09-23 08:18 UTC
Labels: bug
