### ISSUE TITLE
Issue with user confirming workflow: clicking on confirmation link in email throws an error

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#642] opened 2017-02-05 15:42 UTC
This bug is probably related to https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/635; we've had a couple of reports of people being unable to:
- receive a confirmation email and
- confirm their account once the confirmation email was triggered manually

When clicking on the token in the confirmation link, users are directed to a page that throws an internal server error (500). It seems that all users affected ended up with a confirmed account after clicking the link, so the issue might really just be in the page users get redirected to?

**Comment by mkalininait** [comment] 2017-04-06 11:24
May be this error: https://sentry.io/rgsoc/rgsoc-teams/issues/247596626/
(based on what user 2458 wrote to our support).

**Comment by LuisaAPF** [comment] 2017-08-27 19:39
I get an error if I click on the confirmation link while logged out. I could solve this by redirecting to the root path, instead of the sign in path. The difference is that now the user is not automatically signed in. I don't think this might be a problem, as this is the default behavior of devise and is the recommended procedure in terms of security https://stackoverflow.com/questions/18655334/avoid-sign-in-after-confirmation-link-click-using-devise-gem

**Comment by carpodaster** [comment] 2017-08-30 06:58
Would someone find the time to check if this error has been solved by #843? Merci beaucoup!

**Comment by mkalininait** [comment] 2017-09-01 16:21
@carpodaster @LuisaAPF 

>I get an error if I click on the confirmation link while logged out. 

I can't reproduce this anymore. If this is the only use case when we get the error described in the issue, then we can probably close it 👍

**Comment by carpodaster** [comment] 2017-09-01 18:21
I have never been able to reproduce the error deterministically

**Closed** 2017-09-01 19:05 UTC
Labels: bug, high-priority

**Comment by klappradla** [comment] 2017-09-07 16:55
I at the time forgot to comment it on #843, but I could reproduce the problem locally and then have the new code fix it @carpodaster. So I guess it's fine 🙈
