### ISSUE TITLE
Github Handle saving empty fields

### ISSUE THREAD

**Issue by juuh42dias** [rails-girls-summer-of-code/rgsoc-teams#794] opened 2017-07-17 19:58 UTC
GithubHandle returning false or nil class when edit/update your team.

![erro](https://user-images.githubusercontent.com/1828204/28287152-febb46ae-6b10-11e7-9f35-015d10026a2e.png)

**Comment by carpodaster** [comment] 2017-07-18 07:56
Hey @juuh42dias – good call. I've seen this error around but never really looked into it.

The problem is line 9: it does not return / assign the `user` instance variable. This causes the error in the following line (it tries to call a method on `false`).

Can you transform line 9 to something that safely returns a user instance and/or guards against illegal values for `github_handle` alltogether?

**Comment by juuh42dias** [comment] 2017-07-18 12:06
I believe that method first_or_initialize (return find or new) should return an instance to save(blank or not). I think github_handle.present? maybe don't necessary. What do you think?

**Comment by carpodaster** [comment] 2017-08-30 21:18
I'm closing this one, I'm positive it has been fixed with the referenced PR

**Closed by carpodaster** 2017-08-30 21:18 UTC
Labels: bug
