### ISSUE TITLE
Rework team-forming process: no mentors, other student and coaches get invite

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#363] opened 2016-02-03 21:07 UTC
Non-orga people can no longer add mentors to their teams.

Coaches added to the team will get an invite notification they can accept. Only then will they appear on the roster.

Idea: Even adding the 2nd student should be done by invite. As long as the "team" doesn't have a 2nd student, it will not be a `confirmed` team (adding a state machine here?) and it will not appear in the list of teams on the website.

Once the 2nd student accepts the invitation, the teams gets confirmed and is officially created.

**Comment by carpodaster** [comment] 2016-02-15 12:04
@ramonh @lucaspinto Whould anyone of you have time to work on this this week?

**Comment by ramonh** [comment] 2016-02-15 12:05
Sure thing @carpodaster I'll give it a go :)

**Comment by ramonh** [comment] 2016-02-15 12:07
What I'll try to do is break this into smaller pieces:

- Remove Mentors
- Remove and add coach 'invite' system
- Remove and invite second student, migrate to state machine

**Comment by carpodaster** [comment] 2016-02-15 12:14
Cool, @ramonh !

I would implement the other-student-invite first since only after accepting the invitation do we have an actual `confirmed` team (it may be `pending` first, in terms of the state machine).

I would leave the logic of a team to generally contain mentors or any other role (like supervisors later on). We just have to ensure that a team can only ever be created on the public website with 1st) another student and 2nd) one or more coaches, all of which have to accept an invitation.

Removing the second student should probably mean the entire team gets destroyed?

**Comment by ramonh** [comment] 2016-02-15 12:16
Makes sense, thank you @carpodaster. 

If I understood correctly then, it would be best for the team not to be `confirmed` until both a second student and at least one coach accept their invitations, correct?

**Comment by carpodaster** [comment] 2016-02-15 12:19
I would drop the requirement of having at least one coach to have a `confirmed` team. Pure pragmatic reasons: a confirmed team should be able to create an application draft. They can start filling out their stuff without having to wait for a coach to hop on (they may still be in the process of finding any).

**Comment by ramonh** [comment] 2016-02-15 12:19
Got it. I'll start having a look today. Thanks for your help! :+1:

**Comment by carpodaster** [comment] 2016-02-15 12:21
No, thank _you_, sir :)

**Comment by ramonh** [comment] 2016-02-15 12:21
:smile:

**Comment by lucaspinto** [comment] 2016-02-15 13:16
Alas, I won't have time before Saturday.

**Comment by ramonh** [comment] 2016-03-06 16:08
This probably has been answered elsewhere, but I can't seem to find it.

I've just about wrapped up the team revamping (#386), and have only the mentors to remove.

What are the consequences of coaches not being confirmed? Should students be blocked from finalizing the application? This makes sense to me.

@alicetragedy or @carpodaster, what are your thoughts?

**Comment by alicetragedy** [comment] 2016-03-06 16:12
@ramonh yes, I'd say that's how it should work. Maybe it sucks a bit for last-minute applications, but I don't really see any other way — other than a way of still submitting the application and `flagging` it, but we have no time for this right now. After all, this is in the requirements, so they should not be able to submit an application without.

**Comment by ramonh** [comment] 2016-03-06 16:29
Sounds good, thank you for getting back to me so swiftly @alicetragedy! I'll get on it, then

**Comment by carpodaster** [comment] 2016-03-07 13:49
@ramonh @alicetragedy What do you think about displaying an error box at the top of the application form when there aren't any confirmed coaches? Something like "Attention: there are currently no (confirmed) coaches on your team."

**Comment by ramonh** [comment] 2016-03-07 13:50
I like the sound of this, @carpodaster! Are you suggesting though that we allow students to apply without confirmed coaches?

**Comment by carpodaster** [comment] 2016-03-07 13:55
They shouldn't be able to _apply_ I don't think, but they should be able to start filling out the application form (draft). I was thinking about the alert box to avoid any last minute surprises as @alicetragedy mentioned.

**Comment by ramonh** [comment] 2016-03-07 13:56
Ah good, yes, make sense to me. Thanks for clarifying! I'm on it.

**Comment by ramonh** [comment] 2016-03-08 19:15
@alicetragedy, @carpodaster: I added the above suggestion about warning applicants when not all coaches have confirmed. You can find this in #386

**Comment by ramonh** [comment] 2016-03-08 19:40
I also added the requirement that all coaches confirm their membership when submitting the application!

**Comment by alicetragedy** [comment] 2016-03-08 20:35
awesome, thanks @ramonh. had a pretty full day and will not be able to take a look before tomorrow-ish..

**Comment by alicetragedy** [comment] 2016-03-09 21:31
this is done and we can close, right @carpodaster @ramonh?

**Comment by carpodaster** [comment] 2016-03-09 22:51
I wanna leave this open as a reminder that I have to remove the mentor-email-ping still

**Comment by carpodaster** [comment] 2016-03-09 22:56
Also @ramonh I reckon we skip the invite-system for the 2nd student, right? Not only is it yet more work to actually program it, but it also adds another level of testing it (with our group of volunteers I mean)

**Comment by ramonh** [comment] 2016-03-10 09:12
Yes, I think that's a good idea for now, @carpodaster. We have that requirement in place that two students need to be in a team.

**Comment by ramonh** [comment] 2016-03-14 12:05
Hey @carpodaster, if you like I can look into removing the mentor-email-ping :)

**Comment by carpodaster** [comment] 2016-03-14 22:03
@ramonh I am thinking to keep the mentor-email-ping: We probably still gonna add a mentor to a team, just only manually when the teams are selected. wdyt?

**Comment by ramonh** [comment] 2016-03-14 22:04
I like that. I'll just remove the requirement then, if that works?

**Comment by ramonh** [comment] 2016-03-14 22:05
Scratch that, just saw the update. Thanks @carpodaster!

**Comment by mkalininait** [comment] 2016-03-14 22:07
@carpodaster I thought that Laura sends emails to mentors herself. Let's see what she says about this. @alicetragedy

**Comment by alicetragedy** [comment] 2016-03-15 07:17
@mkalininait I do send emails to mentors, but they're usually updates about the program and their next steps — I don't email them about being added to a team or anything like that — I'd leave that up to the robots ;)
@carpodaster @ramonh I'm getting a bit confused here about the process and changes so let me just summarize the requirements:
a team of two students apply with min. one project, max. two projects (they cannot apply without) which is/are selected from a dropdown list (removing "human" errors related to not spelling project name properly, etc.) — I think that the mentor who is attached to each selected project (we have a name and a github handle) should be added to the team and get an email about it.

As an alternative, a team could be valid (to apply) without a mentor (because we have a validation on project anyway so they can't apply without a project; last year the process was different and the mentor in the team ensured we knew which project each team was attached to), and we pull the mentor information into the team when the team is officially selected. 

Not sure whether any of those scenarios have any impact on the mentor "faving" that happens after the applications close and before the teams are selected.

**Comment by carpodaster** [comment] 2016-03-15 08:34
@alicetragedy All your assumptions on how a team can apply are valid and that's how we implemented it (barring existing bugs of course).

You are absolutely right that we can infer a team's mentor from their 1-2 appications. However, we currently do not auto-assign a mentor and my idea was that we assign the mentor the old-school way (i.e. by adding the role mentor to the team as an organizer) for accepted teams, just as we assign supervisor. This is why I suggested leaving the automatic "you have been assigned a mentor for team X" email as is.

You raise a good point about the mentor pick (#364), though. Closing that issue will have to include finding a way to auto-assign the mentors and I already have an idea.

So @alicetragedy and @ramonh: with your permission, I'd like to close this issue. We can carry on in #364.

**Comment by alicetragedy** [comment] 2016-03-15 08:36
:+1:

**Comment by alicetragedy** [comment] 2016-03-15 08:37
is a team, though, still required to have a mentor to apply? If so, this should probably be changed (if we auto-assign mentors after a team has been selected only). 
Other than that, I give my approval for closing this issue!!

**Comment by carpodaster** [comment] 2016-03-15 08:39
@alicetragedy aye, the mentor requirement was removed in 6f1c1e58bb4406c56778f50d4335043721faaf4d

**Comment by alicetragedy** [comment] 2016-03-15 08:40
sorry, should have read the backlog. :facepalm:

![2744956](https://cloud.githubusercontent.com/assets/3143348/13771982/e9f2e4e4-ea91-11e5-8cac-865194c6677e.gif)

**Comment by carpodaster** [comment] 2016-03-15 08:41
Pff, nah! Too many commits!

**Comment by ramonh** [comment] 2016-03-15 08:53
Agreed, I think this is okay to close!

**Comment by alicetragedy** [comment] 2016-03-15 09:09
![image](https://cloud.githubusercontent.com/assets/3143348/13772740/0714e6a4-ea96-11e5-9b5e-bb547a364bd5.png)

**Closed** 2016-03-15 09:11 UTC
