### ISSUE TITLE
Add link to user (mentor) in single project overview

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#647] opened 2017-02-08 11:09 UTC
As we discussed some time ago with @carpodaster, it would be useful to have a link to the teams app user who submitted the project (i.e. mentor) on the overview of each project (right now we just show a link to the github profile of the mentor) so that interested students/teams are able to contact them. 

Note: mentors have been informed that they can provide additional / preferred ways of contact, for example a mailing list or link to IRC/slack/gitter, if they want to, which will be added to the project description as a “Note to Students”.

Maybe next year we could think about adding an additional field: “How to contact the mentor” or something like that, so mentors can input their preferred way of being contacted.

**Comment by mkalininait** [comment] 2017-02-08 17:36
While working on this task I discovered that `@project.mentor` is always null, as long as it is not equal to `@project.submitter`. As we discussed in the dev channel in Slack, we could implement Issue #342 or choose an easier solution and state that project mentors must submit their projects themselves (meaning that we would always count project submitters for primary mentors).

**FYI:** This year (2017) we had 58 project submissions. Three of them have `submitter.github_handle != mentor_github_handle`:
 * [The Processing Foundation](https://teams.railsgirlssummerofcode.org/projects/155-the-processing-foundation) - has 2 mentors
 * [Wikimedia Foundation](https://teams.railsgirlssummerofcode.org/projects/157-wikimedia-foundation)
 * [OpenDF](https://teams.railsgirlssummerofcode.org/projects/165-opendf)

(all have been accepted)

If we choose the easier solution, then the question is what we do with the mentor fields on the project submission form:
* Mentor name
* Mentor github handle
* Mentor email

We could **a) just hide them** or **b) rename them to "Additional mentor name/github_handle/email"** (and then we allow projects to have multiple mentors and students to see them all). On the project page, we could then display:
 * "Submitter / Primary mentor" (we don't display with field at the moment)
 * Additional mentors (what's currently called "Mentor")

That do you think?

**Comment by mkalininait** [comment] 2017-02-08 18:13
Or, we can ignore my previous comment for the moment and just implement a super quick solution for this task:
 * show links to the Teams app for those projects where `submitter.github_handle = mentor_github_handle` (95% of all projects)
 * leave everything as is (no links) for those projects where `submitter.github_handle != mentor_github_handle` (5% of all projects)

![joxi_screenshot_1486576221858](https://cloud.githubusercontent.com/assets/1745735/22750840/8e4e4962-ee32-11e6-81c8-20b4b160c468.png)
![joxi_screenshot_1486577415159](https://cloud.githubusercontent.com/assets/1745735/22750841/8e4eb00a-ee32-11e6-8832-90d29d9a715f.png)

**Comment by alicetragedy** [comment] 2017-02-09 10:22
@mkalininait I think the latter is a good compromise. Besides, two out of the three projects (Processing and Wikimedia) have offered their preferred ways of being contacted in the project overview anyway, so the only one that doesn't offer information on contacting the mentor is OpenDF. I will get in touch with them (OpenDF submitter and mentor) and ask which information we should provide in the project overview.

**Comment by mkalininait** [comment] 2017-02-09 10:28
@alicetragedy Ok.

**Comment by alicetragedy** [comment] 2017-02-10 10:46
Quick note: We should probably check that/if email addresses are visible for students, because right now, user addresses are **not** visible for users that are not logged in. 🙈

**Comment by mkalininait** [comment] 2017-02-10 11:14
@alicetragedy you are right, the emails are not visible to users, even if they are signed in and confirmed 😂 🙈 I'll look into it.

**Comment by alicetragedy** [comment] 2017-02-10 11:18
![crying-pikachu](https://cloud.githubusercontent.com/assets/3143348/22825007/08c912cc-ef8b-11e6-845e-38b6c2a6be13.gif)

**Comment by carpodaster** [comment] 2017-02-10 11:49
Hm. They _should_ be visible unless a user has explicitely checked the "I don't want my email address to be published EVA!" option.

**Comment by mkalininait** [comment] 2017-02-10 12:01
@carpodaster Hmmm... As a *confirmed* teams app user (**@unknownuser365**, id 1613) I don't see any emails, even those of the users who didn't hide their emails (e.g., **@mkalininait**, id 622).

![screen shot 2017-02-10 at 12 56 36](https://cloud.githubusercontent.com/assets/1745735/22826025/86b98504-ef90-11e6-98d0-3936c41e7f4d.png)
![screen shot 2017-02-10 at 12 56 46](https://cloud.githubusercontent.com/assets/1745735/22826026/86ba5196-ef90-11e6-93a4-ce11a6d23b80.png)

There is a check here app/views/users/show.html.slim
```
      - if can? :read, :users_info
        dt E-Mail
        dd = link_to @user.email, "mailto:#{@user.email}" if @user.email.present?
        dt Timezone
        dd = @user.timezone
```

If someone knows how to fix it quickly, that would be cool. I still have tasks on my plate for today. Otherwise I'll look into it on the weekend.

**Comment by mkalininait** [comment] 2017-02-12 11:08
I looked into the code. How it works now:
 * Only users with the roles Admin and Supervisor can see emails and timezones of other users.
 * The checkbox "Never show my email address" doesn't do anything (probably because there is no need in it, see the previous statement).

When easiest thing I could do it to show emails and timezones to *all* confirmed users, if the checkbox "Never show" is false, and to *nobody* if the checkbox is true. But I don't think that this is the right thing to do. At least, there should be roles that see email addresses regardless the `hide_email` value (admins, orga, supervisors?). 

@alicetragedy what do you think? How should it work?

**Comment by alicetragedy** [comment] 2017-02-12 11:13
I think emails should be visible to admins and orgas regardless. :)

otherwise, the rest of the solution you outlined (showing emails to all other confirmed users unless the checkbox is checked) makes a lot of sense. 👍 
About the supervisors: I would probably think it through a bit more and then decide if they should be added to the list of people who can view emails regardless of what the checkbox says. Right now they anyway get the contact information of their teams through the supervisor lead, so I don't think they require to view this info through the teams app. (and it would have to be a complicated thing like: users who are supervisors in the current season can only view hidden information of members of their team).

I hope that helps! thanks!!

**Comment by mkalininait** [comment] 2017-02-12 12:46
@alicetragedy Btw, do you know why we hide timezones together with emails? I can't think of a reason. Can we display the Timezone field like all other normal fields?

**Comment by alicetragedy** [comment] 2017-02-13 13:14
@mkalininait I'm not sure really.. I think it's ok to show this as well. 👍

**Comment by carpodaster** [comment] 2017-04-12 20:20
Is this done now that PR #684 is merged?

**Comment by mkalininait** [comment] 2017-04-12 20:31
Yes!

**Closed by mkalininait** 2017-04-12 20:31 UTC
