### ISSUE TITLE
[Conferences] #7: Assigning a conference

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#771] opened 2017-06-24 13:29 UTC
The idea: https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/751#issuecomment-308574743
Full list of conference user stories: https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/751#issuecomment-309138513

**User Story:**
As an RGSoC orga, I want to see team's conference preferences and assign one or multiple conferences from the longlist which are actually willing to give them free tickets (with an optional comment).

**Things to do:**
1. Who can assign a conference:
 - Orga
2. Who can see offered conferences:
 - Students of this team
 - Supervisors
 - Orga
3. On the team edit form add:
 - h3 Conference offers
 - (dropdown) Offered conference (gets values from the conference longlist)
 - (button) Add another conference (adds another dropdown "Offered conference #2" etc) *
 - (text area) Comment (optional)
 - Change h2 Conference preferences to h3 Conference preferences
 - Add h2 Conferences (above h3 Conference preferences and h3 Conference offers)
4. On the team view page add:
 -  h4 Conference offers
 - Offered conference: Value
 - (if present) Offered conference #2: Value (etc) * 
 - Orga comment
 - Add h3 Conferences (above h4 Conference preferences and h4 Conference offers)

\* ⚠️ In most cases there will be only one offer, in some cases two, in very very very rare cases more than two. To make things simpler, we can implement two fields "Conference offer" and "Conference offer 2" instead of making the button.

Additionally, please pay attention to this comment: https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/771#issuecomment-315903651

**Comment by klappradla** [comment] 2017-07-15 19:02
Hey @mkalininait ,

I'm pretty late to the party, but @F3PiX brought this up and I think it would make sense to at least consider it before we this issue is picked up.

In order to implement the "assigning conferences" feature you describe here, it could make sense to migrate the current `Attendance` model to a `ConferencePreference` model. The way this is currently set up and being implemented in #789, students pick their preferred conferences within their settings / profile pages, however, under the hood the created entity is already called `Attendance`, even though it's *"just"*  a **"preference"** for now 😉 
Having create "attendances" for their preferences sound semantically wrong and is already causing some confusion in #789 ...

The main motivation for distinguishing these things in my opinion would be: having future developers an easier understanding of the terms plus keeping both entities `ConferencePreference` and `ConferenceAttendance` rather simple in themselves.

What do you think? (cc @carpodaster )

**Comment by branquinhoaa** [comment] 2017-07-17 20:07
In fact, I am a little bit confused about this. Now have 2 attendances for each team - first and second options preferences. But we also have to confirm it (what sounds more like an attendance). So, in this case, the attendance model has two meanings: Confirm attendance and save team preferences.

**Comment by klappradla** [comment] 2017-07-17 22:28
Yep @branquinhoaa exactly 🙈 that's also the problem I see.

I'd love to have another opinion by maybe @mkalininait or @carpodaster about this *(also due to the fact that I'm not too familiar with the whole conferences feature)*.

In my opinion it would be most obvious if we would distinguish between three things:
1. `Conference`
2. `ConferencePreference`
3. `ConferenceAttendance`

On the other hand, one could also view the `Attendance` model as a kind of statemachine: initial state would be sort of an *"attendance-request"* and the later state would then be *confirmed*. 

Both valid approaches... Therefore I'd like to have another opinion before we introduce too many changes 😉

**Comment by mkalininait** [comment] 2017-07-19 22:23
Hey @klappradla Thanks for bringing this up. I absolutely agree with you. I think it makes sense to distinguish those three things you listed. In fact, I was thinking of the same model initially. 
I didn't provide details to this task yet, because the previous conf tasks (2-6) were not done yet, so I thought there was no rush :) I will add more info in the task description asap.

**Comment by branquinhoaa** [comment] 2017-07-20 17:41
@mkalininait We are changing the Attendance model to ConferencePreference in pr #789 . The ConferenceAttendance model will be created just on this issue right?

**Comment by klappradla** [comment] 2017-07-20 21:21
Perfect @mkalininait 💚 

And yes @branquinhoaa totally agree with what you're saying. I'd prefer to have #789 merged and cleaned up before introducing yet another model. The first step in this would probably be: renaming the current `Attendance` model to `ConferencePreference`. This could be done in the current PR, but it's not super necessary. I'd personally prefer a 2nd PR, since smaller ones are easier for me to review.

**Comment by mkalininait** [comment] 2017-07-21 07:39
@branquinhoaa Yes, this is how I see it, too.

**Comment by branquinhoaa** [comment] 2017-08-03 14:24
@mkalininait and @klappradla 
I was thinking about the models and maybe instead of a ConferenceAttendance model, it will make more sense to build a ConferenceOffer model. 
Each team will have one (or many?) ConferenceOffer with conference_id, team_id, orga_comment, and attendance(boolean).  
We have here the same issue that we had in ConferencePreferences (a table with some data for the relationship -> orga_comment,  and some data for each conference -> attendance).

What is the best approach in this case?

**Comment by klappradla** [comment] 2017-08-03 21:51
I'm not sure if the issue is entirely the same as with `ConferencePreferences` @branquinhoaa ? The only attribute that is kind of _"interfering"_ with a simple solution (one `ConferenceOffer` for one `Conference`) is the orga comment.

But for me there are still some open questions:
1. What's the orga comment for? (cc @mkalininait)
1. Who can see the orga comment? I suppose the team will see it later on as a hint on why they've been chosen, telling them they'll receive more infos for their talk, etc.
1. Is the orga comment relevant **before** the `ConferenceOffer` is created / visible to students? I suppose not.

All in all - please correct me if I'm totally off @mkalininait - the comment is going to be **optional** and is not related to the combination of `Conferences` the team chose in their `ConferencePreference`, but to a **single `Conference`** out of their preferences they're then offered to go to.
It's also most likely, that a team will simply get a single `ConferenceOffer` for one `Conference` outta the two they chose in their `ConferencePreference`.

The mental model for the `ConferenceOffer` would then be: have all the conference-tuples from the teams' `ConferencePreferences` as a base data to decide which Team to give which `ConferenceOffers`. Therefore, the `ConferenceOffer` needs a 1x1 association with a `Conference`, but **does not stand in any association** with the `ConferencePreference` object from the team.
This idea could even be extended to: a team can get a `ConferenceOffer` for a `Conference` they did not even mention in their `ConferencePreference`.

Given that, I think your 2nd approach sounds best 👍 

Feel fee to ping me if anything about the ☝️ is unclear or if I got something wrong.

**Comment by mkalininait** [comment] 2017-08-04 11:01
Hey @klappradla @branquinhoaa 

There indeed can be a situation when we offer a conference which hasn't been selected as a team preference. It's not a super rare case. Not all the conferences want to support RGSoC. Thus we need to choose our offer from the full list of conferences.

On the other hand, some conferences offer more than 2 tickets. This means that we can offer one conference to several teams. It's not a rare case either. Thus the association between a `ConferenceOffer` and a `Conference` could probably be many-to-many (one offer can have many conferences; one conference may be in several offers). If we simplify the model and say that one team can be offered 2 conferences max, then the `ConferenceOffers` model looks almost the same as the `ConferencePreferences` model to me. 

This is how I see it.

To your questions Max:
1. The orga comment is for the students; it can provide additional information about an offer/offers (e.g. a conference is providing a LT slot; promo codes to register for a conference; opportunity to get a diversity grant etc.)
2.  The team should see the orga comment together with the offered conference/conferences.
3. The orga comment is not relevant in the absence of a conference offer.
4. The orga comment is optional and not related to team's conference preferences; it's related to all offered conferences (usually one or two). We could do one comment per offer, but I think it's a bit excessive; one comment for all offers should be enough.

**Comment by klappradla** [comment] 2017-08-06 12:37
Thanx for explaining @mkalininait 💚 

I knew a `Conference` could be part of many `ConferenceOffers`, sorry if that wasn't clear enough in my previous comment.

So, just to illustrate things, I thought it would look like this:
![untitled diagram 3](https://user-images.githubusercontent.com/3491815/29003266-d85f06fa-7ab3-11e7-8048-af1fe1fd7fa5.png)

Which means: one `ConferenceOffer` for a `ConferencePreference`'s `Choice 1` and one for `Choice 2`. I would have the comment to be imagined something like
> If you pick this conference, your lightning talk will be on the main track.

But if the offer is always looked at as a whole package of 2 conferences, then your approach of aligning it with the `ConferencePreference` probably makes more sense.

**Comment by mkalininait** [comment] 2017-08-06 18:27
@klappradla Great diagrams, Max! They make thigs clear. 
I think both of them make sense from different angles of view. The Conference Offers are similar to the Conference Preferences, because they have one comment for all assigned (offered or prefered) conferences (at least in my mind :)). However the difference is that while students usually choose two preferences, they usually get only one offer, and only in some cases two. 
I'm torn.

**Comment by klappradla** [comment] 2017-08-06 21:35
Hm, if a team getting offered 2 conferences is the rarer, more exceptional case, we should probably build things with this as the main scenario in mind and don't treat the comment as such an important part of the whole workflow _(especially if it's optional)_

So what about this:
We take the first approach (one `ConferenceOffer` per `Conference`)  at let a `Team` have `0..*` of them (this would also allow to offer 3 conferences, etc.)

**Contra:** the comment is targeted at a single `Conference` rather then the "whole offer"

**Pro:** this is technically speaking already an `Attendance` and could be a) renamed to have this meaning and b) contain the necessary boolean or whatever to confirm "yes, the team is going".

![conferences 1](https://user-images.githubusercontent.com/3491815/29007288-d7130fde-7aff-11e7-8666-46d37e899c07.png)

**Comment by branquinhoaa** [comment] 2017-08-07 12:51
@mkalininait what do you think? Can we use this approach?

**Comment by mkalininait** [comment] 2017-08-07 12:56
@klappradla @branquinhoaa Yes! Let's do this!

**Comment by branquinhoaa** [comment] 2017-08-07 17:47
@mkalininait I have one more question:

- Just an orga member can assign a conference for a team.  Is it necessary to put the fields to assign conference into teams/form? or just into orga/teams/form is enough?

**Comment by klappradla** [comment] 2017-08-07 20:01
Hey @branquinhoaa this should ideally live in the `orga` namespace. And it does not need to be a `team`-form after all - it can simply be a `ConferenceAttendance` form.
The controller you're using for this can inherit from the `OrgaBaseController` (don't know the exact name now), which already makes sure that the user has the required role for all the actions he or she want to perform.

Does that answer your question?

**Comment by branquinhoaa** [comment] 2017-08-07 20:20
I thought it would be done in the team's controller. I'm going to change it.

**Comment by klappradla** [comment] 2017-08-07 20:29
Oh @branquinhoaa no, do as you think it makes sense.
I just wanted to point out: it should ideally be in the orga namespace - can therefore also be the teams controller in the orga namespace.

**Comment by branquinhoaa** [comment] 2017-08-07 20:33
I reopened the PR for you to see how I did it. If it is better to move to another controller, fine, I can fix that in the same PR.

**Comment by klappradla** [comment] 2017-08-07 20:37
Alright, thanx 🙏 
I don't think I'll find the time to review it today - already too 😴 - so feel free to just request a review by me and I'll have a look tomorrow / as soon as I can get to it.

**Closed** 2017-08-14 21:47 UTC
Labels: in progress
